package dev.sylvyespvphud;

import com.google.gson.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.*;

/** Compact offline profile formats. New exports use SPH2; SPH1 remains importable. */
final class ProfileClipboard {
    static final String PREFIX="SPH2:",ASCII_PREFIX="SPH2A:",LEGACY_PREFIX="SPH1:";
    static final int DISCORD_LIMIT=2000;
    private static final int MAX=1_048_576,CJK=0x4e00;
    private static final Gson GSON=new GsonBuilder().disableHtmlEscaping().create();
    private static final String[] FIELDS=("alignX alignY anchorX anchorY attributeSwap attributeSwaps audioEndInterval audioStartInterval bassPitch bassVolume boldCriticalDamage calculatedDamage color combinedColor combinedText damage damageIndicatorColor damageIndicatorEnabled damageIndicatorOpacity damageIndicatorThickness damageTracker displayMode distanceScalingStrength elytraOnly enabled fall fallColor fallColors fallEnabled fallSize fallTemplate fallThreshold fallX fallY flatColor hardToReachMode harpPitch harpVolume healing healingEnabled healingItems healingSize healingX healingY healthColor healthPercent healthText hideDistantPlayers hideLocatorBar hideStartDistance hit hitColor hitColors hitEnabled hitSeconds hitSize hitTemplate hitX hitY hud icon iconSize intensity item keys maceEnabled maxDisplacement maximum maxVisiblePlayers minimum minimumReachableArea mode onlyWhenPlayerListHeld opacity pitch playerTracker position potion radius reachOutlines reticleEnabled retotem retotemColor retotemEnabled retotemSize retotemText retotemX retotemY saturationColor saturationItems saturationText saturationThreshold scale schemaVersion secondaryColor sensitivity showDistance size sound soundEnabled soundId sounds spearEnabled spearOnly stationaryThreshold successfulHitOnly survival swordAxeEnabled targetPitch thickness thirdPerson topFacesOnly trackerEnabled trackerHudAlwaysVisible trackerHudSeconds trackerSeconds trackerTemplate useEnemyGear vectors velocity velocityColors velocityEnabled velocityTemplate velocityThreshold visualEnabled volume weaponOnly width x y").split(" ");
    private static final Map<String,Integer> IDS=new HashMap<>();
    static{for(int i=0;i<FIELDS.length;i++)IDS.put(FIELDS[i],i);}
    private record Legacy(int schemaVersion,String name,ProfileSettings settings){}
    static int schemaFieldCount(){return FIELDS.length;}static int schemaFieldId(String name){return IDS.getOrDefault(name,-1);}

    static String encode(SettingsProfile p){return PREFIX+base16384(envelope(p));}
    static String encodeAscii(SettingsProfile p){return ASCII_PREFIX+Base64.getUrlEncoder().withoutPadding().encodeToString(envelope(p));}
    static List<String> discordChunks(SettingsProfile p){String s=encode(p);if(s.length()<=DISCORD_LIMIT)return List.of(s);String b=s.substring(PREFIX.length());int z=1850,n=(b.length()+z-1)/z;List<String> out=new ArrayList<>();for(int i=0;i<n;i++)out.add("SPH2/"+(i+1)+"/"+n+":"+b.substring(i*z,Math.min(b.length(),(i+1)*z)));return List.copyOf(out);}
    static Imported decode(String input){if(input==null)throw bad("Clipboard does not contain a SylvyesPvPHud profile.");String s=input.trim();if(s.startsWith(LEGACY_PREFIX))return legacy(s);if(s.startsWith("SPH2/"))s=join(s);try{byte[] data;if(s.startsWith(PREFIX))data=unbase16384(s.substring(PREFIX.length()));else if(s.startsWith(ASCII_PREFIX))data=Base64.getUrlDecoder().decode(s.substring(ASCII_PREFIX.length()));else throw bad("Clipboard does not contain a SylvyesPvPHud profile.");return decodeEnvelope(data);}catch(IllegalArgumentException e){throw e;}catch(Exception e){throw bad("Shared profile is damaged.");}}

    private static byte[] envelope(SettingsProfile p){try{JsonObject v=GSON.toJsonTree(p.settings().validated()).getAsJsonObject(),d=GSON.toJsonTree(ProfileSettings.defaults()).getAsJsonObject();ByteArrayOutputStream rb=new ByteArrayOutputStream();DataOutputStream r=new DataOutputStream(rb);string(r,p.name());value(r,diff(v,d));r.flush();byte[] plain=rb.toByteArray(),zip=deflate(plain);boolean compressed=zip.length<plain.length;byte[] body=compressed?zip:plain;ByteArrayOutputStream eb=new ByteArrayOutputStream();DataOutputStream e=new DataOutputStream(eb);e.writeByte(compressed?1:0);varint(e,plain.length);varint(e,body.length);e.write(body);CRC32 crc=new CRC32();crc.update(plain);e.writeInt((int)crc.getValue());e.flush();return eb.toByteArray();}catch(IOException e){throw new IllegalStateException(e);}}
    private static Imported decodeEnvelope(byte[] b)throws IOException{DataInputStream in=new DataInputStream(new ByteArrayInputStream(b));int flags=in.readUnsignedByte();if((flags&~1)!=0)throw bad("Unsupported shared profile version.");int plen=readInt(in),blen=readInt(in);if(plen<0||plen>MAX||blen<0||blen>MAX)throw bad("Shared profile is too large.");byte[] body=in.readNBytes(blen);if(body.length!=blen||in.available()!=4)throw bad("Shared profile is damaged.");int expected=in.readInt();byte[] plain=(flags&1)==1?inflate(body,plen):body;if(plain.length!=plen)throw bad("Shared profile has an invalid length.");CRC32 crc=new CRC32();crc.update(plain);if((int)crc.getValue()!=expected)throw bad("Shared profile checksum failed.");DataInputStream data=new DataInputStream(new ByteArrayInputStream(plain));String name=ProfileManager.validateName(readString(data));JsonElement delta=readValue(data);if(data.available()!=0||!delta.isJsonObject())throw bad("Shared profile is damaged.");JsonObject merged=merge(GSON.toJsonTree(ProfileSettings.defaults()).getAsJsonObject(),delta.getAsJsonObject());return new Imported(name,GSON.fromJson(merged,ProfileSettings.class).validated());}

    private static JsonObject diff(JsonObject v,JsonObject d){JsonObject r=new JsonObject();for(var e:v.entrySet()){JsonElement old=d.get(e.getKey()),x=e.getValue();if(old!=null&&x.equals(old))continue;if(old!=null&&x.isJsonObject()&&old.isJsonObject()){JsonObject c=diff(x.getAsJsonObject(),old.getAsJsonObject());if(!c.isEmpty())r.add(e.getKey(),c);}else r.add(e.getKey(),x);}return r;}
    private static JsonObject merge(JsonObject d,JsonObject delta){JsonObject r=d.deepCopy();for(var e:delta.entrySet()){JsonElement old=r.get(e.getKey());r.add(e.getKey(),old!=null&&old.isJsonObject()&&e.getValue().isJsonObject()?merge(old.getAsJsonObject(),e.getValue().getAsJsonObject()):e.getValue());}return r;}
    private static void value(DataOutput out,JsonElement v)throws IOException{if(v==null||v.isJsonNull()){out.writeByte(0);return;}if(v.isJsonArray()){out.writeByte(6);varint(out,v.getAsJsonArray().size());for(JsonElement x:v.getAsJsonArray())value(out,x);return;}if(v.isJsonObject()){out.writeByte(7);varint(out,v.getAsJsonObject().size());for(var e:v.getAsJsonObject().entrySet()){Integer id=IDS.get(e.getKey());if(id==null)throw bad("Unsupported profile field: "+e.getKey());varint(out,id);value(out,e.getValue());}return;}JsonPrimitive p=v.getAsJsonPrimitive();if(p.isBoolean()){out.writeByte(p.getAsBoolean()?2:1);return;}if(p.isString()){out.writeByte(5);string(out,p.getAsString());return;}try{long n=Long.parseLong(p.getAsString());out.writeByte(3);varlong(out,(n<<1)^(n>>63));}catch(NumberFormatException ignored){out.writeByte(4);out.writeLong(Double.doubleToRawLongBits(p.getAsDouble()));}}
    private static JsonElement readValue(DataInput in)throws IOException{return switch(in.readUnsignedByte()){case 0->JsonNull.INSTANCE;case 1->new JsonPrimitive(false);case 2->new JsonPrimitive(true);case 3->{long z=readLong(in);yield new JsonPrimitive((z>>>1)^-(z&1));}case 4->new JsonPrimitive(Double.longBitsToDouble(in.readLong()));case 5->new JsonPrimitive(readString(in));case 6->{int n=count(in);JsonArray a=new JsonArray();for(int i=0;i<n;i++)a.add(readValue(in));yield a;}case 7->{int n=count(in);JsonObject o=new JsonObject();for(int i=0;i<n;i++){int id=readInt(in);if(id<0||id>=FIELDS.length)throw bad("Unknown profile field ID.");if(o.has(FIELDS[id]))throw bad("Duplicate profile field.");o.add(FIELDS[id],readValue(in));}yield o;}default->throw bad("Unknown profile value type.");};}
    private static int count(DataInput in)throws IOException{int n=readInt(in);if(n<0||n>100000)throw bad("Invalid profile collection size.");return n;}
    private static void string(DataOutput o,String s)throws IOException{byte[] b=s.getBytes(StandardCharsets.UTF_8);varint(o,b.length);o.write(b);}
    private static String readString(DataInput i)throws IOException{int n=readInt(i);if(n<0||n>MAX)throw bad("Invalid profile string length.");byte[] b=new byte[n];i.readFully(b);return new String(b,StandardCharsets.UTF_8);}
    private static void varint(DataOutput o,int v)throws IOException{varlong(o,Integer.toUnsignedLong(v));}private static int readInt(DataInput i)throws IOException{return(int)readLong(i);}private static void varlong(DataOutput o,long v)throws IOException{while((v&~127L)!=0){o.writeByte((int)v&127|128);v>>>=7;}o.writeByte((int)v);}private static long readLong(DataInput i)throws IOException{long v=0;for(int s=0;s<64;s+=7){int b=i.readUnsignedByte();v|=(long)(b&127)<<s;if((b&128)==0)return v;}throw bad("Invalid variable integer.");}
    private static byte[] deflate(byte[] raw){Deflater d=new Deflater(9,true);d.setInput(raw);d.finish();ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];while(!d.finished())o.write(b,0,d.deflate(b));d.end();return o.toByteArray();}
    private static byte[] inflate(byte[] body,int n){Inflater i=new Inflater(true);i.setInput(body);byte[] out=new byte[n];try{int got=i.inflate(out);if(got!=n||!i.finished())throw bad("Shared profile compression is damaged.");return out;}catch(DataFormatException e){throw bad("Shared profile compression is damaged.");}finally{i.end();}}
    private static String base16384(byte[] data){byte[] f=new byte[data.length+4];f[0]=(byte)(data.length>>>24);f[1]=(byte)(data.length>>>16);f[2]=(byte)(data.length>>>8);f[3]=(byte)data.length;System.arraycopy(data,0,f,4,data.length);StringBuilder s=new StringBuilder();long bits=0;int count=0;for(byte b:f){bits=bits<<8|(b&255);count+=8;while(count>=14){count-=14;s.append((char)(CJK+((bits>>>count)&16383)));bits&=(1L<<count)-1;}}if(count>0)s.append((char)(CJK+(bits<<(14-count))));return s.toString();}
    private static byte[] unbase16384(String s){ByteArrayOutputStream o=new ByteArrayOutputStream();long bits=0;int count=0;for(int j=0;j<s.length();j++){int v=s.charAt(j)-CJK;if(v<0||v>=16384)throw bad("Shared profile contains invalid characters.");bits=bits<<14|v;count+=14;while(count>=8){count-=8;o.write((int)(bits>>>count)&255);bits&=(1L<<count)-1;}}byte[] a=o.toByteArray();if(a.length<4)throw bad("Shared profile is damaged.");int n=(a[0]&255)<<24|(a[1]&255)<<16|(a[2]&255)<<8|(a[3]&255);if(n<0||n>MAX||n>a.length-4)throw bad("Shared profile has an invalid length.");return Arrays.copyOfRange(a,4,4+n);}
    private static String join(String text){String[] lines=text.split("\\R+");Map<Integer,String> p=new HashMap<>();int total=-1;for(String line:lines){line=line.trim();if(line.isEmpty())continue;int colon=line.indexOf(':');if(colon<0)throw bad("Invalid Discord profile chunk.");String[] h=line.substring(0,colon).split("/");if(h.length!=3||!h[0].equals("SPH2"))throw bad("Invalid Discord profile chunk.");int part,n;try{part=Integer.parseInt(h[1]);n=Integer.parseInt(h[2]);}catch(Exception e){throw bad("Invalid Discord profile chunk.");}if(total<0)total=n;if(total!=n||part<1||part>n||p.put(part,line.substring(colon+1))!=null)throw bad("Mixed or duplicate Discord profile chunks.");}if(total<1||p.size()!=total)throw bad("Discord profile chunks are missing.");StringBuilder s=new StringBuilder(PREFIX);for(int i=1;i<=total;i++)s.append(p.get(i));return s.toString();}
    private static Imported legacy(String s){try{byte[] z=Base64.getUrlDecoder().decode(s.substring(LEGACY_PREFIX.length()));ByteArrayOutputStream o=new ByteArrayOutputStream();try(GZIPInputStream g=new GZIPInputStream(new ByteArrayInputStream(z))){byte[] b=new byte[8192];int n;while((n=g.read(b))>=0){if(o.size()+n>MAX)throw bad("Shared profile is too large.");o.write(b,0,n);}}Legacy x=GSON.fromJson(o.toString(StandardCharsets.UTF_8),Legacy.class);if(x==null||x.schemaVersion()!=1)throw bad("Unsupported shared profile version.");return new Imported(ProfileManager.validateName(x.name()),x.settings().validated());}catch(IllegalArgumentException e){throw e;}catch(Exception e){throw bad("Shared profile is damaged.");}}
    private static IllegalArgumentException bad(String s){return new IllegalArgumentException(s);}
    record Imported(String name,ProfileSettings settings){}
}
