package dev.macepvpmod;

import java.io.IOException;
import java.util.function.*;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.layouts.LinearLayout;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

/** Complete settings workspace; module pages edit one shared draft directly. */
public final class SettingsScreen extends Screen {
    private static final String[] PAGES={"Overview","Pitch Bar","Damage","Attribute Swaps","Survival","Reach Outlines","Vectors","Player Tracker","HUD Studio"};
    private static final String[] HUD={"Pitch bar","Fall distance","Hit damage","Retotem","Healing","Attribute swap","Velocity"};
    private final Screen parent;private final SettingsSession draft;private final boolean[] expanded=new boolean[28];private int page,tab,hudElement,sidebar,contentX,contentW;private String error="";private Button apply;
    public SettingsScreen(Screen parent){super(Component.translatable("macepvpmod.settings.title"));this.parent=parent;draft=new SettingsSession();}

    protected void init(){sidebar=Math.min(168,Math.max(118,width/3));contentX=sidebar+14;contentW=Math.max(170,width-contentX-14);buildSidebar();var rows=LinearLayout.vertical().spacing(6);
        switch(page){case 0->overview(rows);case 1->pitch(rows);case 2->damage(rows);case 3->swaps(rows);case 4->survival(rows);case 5->reach(rows);case 6->vectors(rows);case 7->tracker(rows);case 8->hud(rows);}
        var scroll=new ScrollableLayout(minecraft,rows,Math.max(42,height-94));scroll.setMinWidth(contentW);scroll.arrangeElements();scroll.setX(contentX);scroll.setY(44);scroll.visitWidgets(this::addRenderableWidget);
        int w=84,x=width-14;apply=addRenderableWidget(Button.builder(Component.translatable("macepvpmod.settings.apply"),b->apply()).bounds(x-w*2-6,height-27,w,20).build());apply.active=draft.dirty()&&draft.validation().isEmpty();addRenderableWidget(Button.builder(Component.translatable("macepvpmod.settings.cancel"),b->closeRequested()).bounds(x-w,height-27,w,20).build());}

    private void buildSidebar(){int y=40;for(int i=0;i<PAGES.length;i++){int n=i;int toggle=i>0&&i<8?38:0;addRenderableWidget(Button.builder(Component.literal((page==i?"› ":"")+PAGES[i]),b->{page=n;tab=0;rebuildWidgets();}).bounds(8,y,sidebar-20-toggle,20).build());if(toggle>0)addRenderableWidget(Button.builder(Component.literal(draft.enabled(i)?"✓":"—"),b->{draft.toggle(n);rebuildWidgets();}).bounds(sidebar-48,y,36,20).build());y+=21;}}
    private void overview(LinearLayout r){title(r,"Settings overview","Choose a module on the left. Every edit remains a draft until Apply.");card(r,"MODULE STATUS");for(int i=1;i<8;i++){int n=i;row(r,PAGES[i],draft.enabled(i)?"Enabled":"Disabled",button(draft.enabled(i)?"On":"Off",54,b->{draft.toggle(n);rebuildWidgets();}),true);}card(r,"WORKSPACE");note(r,"Complex color, sound, playlist, and item editors return their result to this same draft.");action(r,"Reset everything",()->confirm("Reset all settings?",()->{draft.resetAll();rebuildWidgets();}));}

    private void pitch(LinearLayout r){title(r,"Elytra Pitch Bar","Keep the common flight guide controls visible; technical tuning is grouped below.");card(r,"GENERAL");toggle(r,"Enabled","Show the pitch guide while gliding.",draft.pitch.enabled(),v->draft.pitch("enabled",v),true);toggle(r,"Third-person view","Also show the guide outside first person.",draft.pitch.thirdPerson(),v->draft.pitch("thirdPerson",v),draft.pitch.enabled());card(r,"FLIGHT GUIDE");slider(r,"Target pitch","The approach angle the center line represents.",draft.pitch.targetPitch(),-90,90,.5,v->draft.pitch("targetPitch",v),draft.pitch.enabled());slider(r,"Response","Pixels moved for each degree away from target.",draft.pitch.sensitivity(),.1,10,.1,v->draft.pitch("sensitivity",v),draft.pitch.enabled());slider(r,"Maximum travel","Limits vertical movement on screen.",draft.pitch.maxDisplacement(),0,200,1,v->draft.pitch("maxDisplacement",(int)v),draft.pitch.enabled());advanced(r,()->{slider(r,"Bar width","Exact width is normally edited in HUD Studio.",draft.pitch.width(),10,400,1,v->{draft.pitch("width",(int)v);hudCopyPitch();},true);slider(r,"Thickness","Bar thickness in GUI pixels.",draft.pitch.thickness(),1,8,1,v->{draft.pitch("thickness",(int)v);hudCopyPitch();},true);});appearance(r,0);reset(r);}

    private void damage(LinearLayout r){title(r,"Damage Counter","Fall, hit, and weapon behavior are separated into focused tabs.");tabs(r,"Fall Distance","Hit Damage","Weapons","Appearance");var d=draft.damage;
        if(tab==0){card(r,"FALL DISTANCE");toggle(r,"Show fall distance","Display damage-relevant fall distance.",d.fallEnabled(),v->draft.damage("fallEnabled",v),d.enabled());slider(r,"Visibility threshold","Show only above this many blocks.",d.fallThreshold(),0,20,.1,v->draft.damage("fallThreshold",v),d.enabled()&&d.fallEnabled());template(r,"Fall message",d.fallTemplate(),false);appearance(r,1);}
        if(tab==1){card(r,"HIT DAMAGE");toggle(r,"Show hit damage","Display confirmed outgoing damage.",d.hitEnabled(),v->draft.damage("hitEnabled",v),d.enabled());slider(r,"Display duration","How long the result remains visible.",d.hitSeconds(),1,10,1,v->draft.damage("hitSeconds",(int)v),d.enabled()&&d.hitEnabled());choice(r,"Damage source",d.calculatedDamage()?"Calculated":"Reported",()->draft.damage("calculatedDamage",!d.calculatedDamage()),d.enabled()&&d.hitEnabled());toggle(r,"Use enemy gear","Estimate visible armor and enchantments; temporarily uses a 0–20 color scale.",d.useEnemyGear(),v->draft.damage("useEnemyGear",v),d.enabled()&&d.hitEnabled()&&d.calculatedDamage());toggle(r,"Bold critical hits","Emphasize confirmed vanilla critical hits.",d.boldCriticalDamage(),v->draft.damage("boldCriticalDamage",v),d.enabled()&&d.hitEnabled());template(r,"Hit message",d.hitTemplate(),true);appearance(r,2);}
        if(tab==2){card(r,"WEAPON FILTER");toggle(r,"Mace","Track mace attacks.",d.maceEnabled(),v->draft.damage("maceEnabled",v),d.enabled()&&d.hitEnabled());toggle(r,"Spear","Track spear jabs and charges.",d.spearEnabled(),v->draft.damage("spearEnabled",v),d.enabled()&&d.hitEnabled());toggle(r,"Sword and axe","Track conventional melee weapons.",d.swordAxeEnabled(),v->draft.damage("swordAxeEnabled",v),d.enabled()&&d.hitEnabled());}
        if(tab==3){card(r,"HUD STUDIO");note(r,"Fall and Hit placement, scale, and color gradients are configured with their HUD elements.");appearance(r,1);appearance(r,2);}reset(r);}

    private void swaps(LinearLayout r){title(r,"Attribute Swaps","Feedback and detection rules are intentionally separate.");card(r,"FEEDBACK");toggle(r,"HUD notification","Show a short overlay message.",draft.swap.visualEnabled(),v->draft.swap("visualEnabled",v),draft.swap.enabled());toggle(r,"Sound","Play feedback when a swap is detected.",draft.swap.soundEnabled(),v->draft.swap("soundEnabled",v),draft.swap.enabled());text(r,"Sound ID","Registered Minecraft sound identifier.",draft.swap.soundId(),v->draft.swap("soundId",v),draft.swap.enabled()&&draft.swap.soundEnabled());action(r,"Test sound",()->AttributeSwaps.playSound(draft.swap.soundId()));card(r,"DETECTION");toggle(r,"Weapons only","Ignore swaps to items without weapon attributes.",draft.swap.weaponOnly(),v->draft.swap("weaponOnly",v),draft.swap.enabled());toggle(r,"Successful hits only","Require combat confirmation before detecting the swap.",draft.swap.successfulHitOnly(),v->draft.swap("successfulHitOnly",v),draft.swap.enabled());appearance(r,5);reset(r);}

    private void survival(LinearLayout r){title(r,"Survival Instincts","Warnings, item rules, audio, and damage feedback are separated into focused tabs.");tabs(r,"Totem","Health & Hunger","Audio","Damage Indicator");var s=draft.survival;
        if(tab==0){card(r,"TOTEM WARNING");toggle(r,"Retotem warning","Warn when a carried totem can fill an empty offhand.",s.retotemEnabled(),v->draft.survival("retotemEnabled",v),s.enabled());text(r,"Message","Text displayed by the warning.",s.retotemText(),v->draft.survival("retotemText",v),s.enabled()&&s.retotemEnabled());appearance(r,3);}
        if(tab==1){card(r,"TRIGGERS");toggle(r,"Health and hunger warnings","Enable actionable survival alerts.",s.healingEnabled(),v->draft.survival("healingEnabled",v),s.enabled());slider(r,"Low health","Trigger below this percentage.",s.healthPercent(),0,100,1,v->draft.survival("healthPercent",v),s.enabled()&&s.healingEnabled());slider(r,"Low saturation","Trigger below this saturation value.",s.saturationThreshold(),0,20,.5,v->draft.survival("saturationThreshold",v),s.enabled()&&s.healingEnabled());card(r,"MESSAGES");text(r,"Low health",null,s.healthText(),v->draft.survival("healthText",v),true);text(r,"Low saturation",null,s.saturationText(),v->draft.survival("saturationText",v),true);text(r,"Combined",null,s.combinedText(),v->draft.survival("combinedText",v),true);card(r,"ACTIONABLE ITEMS");itemList(r,"Healing items",s.healingItems(),SurvivalItemRule.healingDefaults(),"healingItems");itemList(r,"Saturation items",s.saturationItems(),SurvivalItemRule.saturationDefaults(),"saturationItems");appearance(r,4);}
        if(tab==2){card(r,"PLAYLIST");row(r,"Warning sounds","One entry plays on each warning beat.",button("Edit "+s.sounds().size(),72,b->minecraft.gui.setScreen(new SoundPlaylistScreen(this,s.sounds(),v->{draft.survival("sounds",v);rebuildWidgets();}))),true);advanced(r,()->{slider(r,"Threshold interval","Seconds between notes at the warning threshold.",s.audioStartInterval(),.05,3,.05,v->draft.survival("audioStartInterval",v),true);slider(r,"Critical interval","Seconds between notes near zero health.",s.audioEndInterval(),.05,3,.05,v->draft.survival("audioEndInterval",v),true);});}
        if(tab==3){card(r,"DAMAGE FEEDBACK");toggle(r,"Damage indicator","Flash a fading border when health or absorption is lost.",s.damageIndicatorEnabled(),v->draft.survival("damageIndicatorEnabled",v),s.enabled());slider(r,"Thickness","Border width in GUI pixels.",s.damageIndicatorThickness(),1,80,1,v->draft.survival("damageIndicatorThickness",(int)v),s.enabled()&&s.damageIndicatorEnabled());slider(r,"Transparency","Higher values make the border more visible.",s.damageIndicatorOpacity()*100,1,100,1,v->draft.survival("damageIndicatorOpacity",v/100),s.enabled()&&s.damageIndicatorEnabled());color(r,"Border color",s.damageIndicatorColor(),v->draft.survival("damageIndicatorColor",v));}reset(r);}

    private void reach(LinearLayout r){title(r,"Reach Outlines","Detection and rendering have separate visual hierarchy.");card(r,"DETECTION");toggle(r,"Top faces only","Ignore side and bottom faces.",draft.reach.topFacesOnly(),v->draft.reach("topFacesOnly",v),draft.reach.enabled());choice(r,"Hard-to-reach faces",draft.reach.hardToReachMode().label(),()->draft.reach("hardToReachMode",draft.reach.hardToReachMode().next()),draft.reach.enabled());slider(r,"Minimum reachable area","Required reachable fraction of a face.",draft.reach.minimumReachableArea()*100,1,100,1,v->draft.reach("minimumReachableArea",v/100),draft.reach.enabled());card(r,"RENDERING");slider(r,"Intensity","Outline opacity.",draft.reach.intensity()*100,2,100,1,v->draft.reach("intensity",v/100),draft.reach.enabled());slider(r,"Thickness","Outline width in pixels.",draft.reach.thickness(),1,ReachOutlineConfig.MAX_THICKNESS,1,v->draft.reach("thickness",(int)v),draft.reach.enabled());color(r,"Outline color",draft.reach.color(),c->draft.reach("color",c));reset(r);}

    private void vectors(LinearLayout r){title(r,"Vectors","See motion direction and speed at a glance.");tabs(r,"Reticle","Velocity");var v=draft.vectors;
        if(tab==0){card(r,"MOTION RETICLE");toggle(r,"Show reticle","Shows where to look to align with current velocity.",v.reticleEnabled(),n->draft.vectors("reticleEnabled",n),v.enabled());card(r,"WHEN TO SHOW");toggle(r,"When gliding","Allow while actively gliding.",v.elytraOnly(),n->draft.vectors("elytraOnly",n),v.enabled()&&v.reticleEnabled());toggle(r,"When charging","Allow while charging a spear attack.",v.spearOnly(),n->draft.vectors("spearOnly",n),v.enabled()&&v.reticleEnabled());note(r,"With both filters off, the reticle is unrestricted.");card(r,"APPEARANCE");choice(r,"Icon",v.icon().label(),()->draft.vectors("icon",v.icon().next()),v.enabled()&&v.reticleEnabled());slider(r,"Size","Icon size in GUI pixels.",v.size(),3,31,2,n->draft.vectors("size",(int)n),v.enabled()&&v.reticleEnabled());slider(r,"Opacity",null,v.opacity()*100,5,100,1,n->draft.vectors("opacity",n/100),v.enabled()&&v.reticleEnabled());slider(r,"Stationary threshold","Hide below this speed in blocks/second.",v.stationaryThreshold(),0,20,.05,n->draft.vectors("stationaryThreshold",n),v.enabled()&&v.reticleEnabled());color(r,"Reticle color",v.color(),n->draft.vectors("color",n));}
        if(tab==1){card(r,"VELOCITY READOUT");toggle(r,"Show velocity","Display speed in blocks per second.",v.velocityEnabled(),n->draft.vectors("velocityEnabled",n),v.enabled());slider(r,"Display threshold","Hide at or below this speed in blocks/second.",v.velocityThreshold(),0,20,.05,n->draft.vectors("velocityThreshold",n),v.enabled()&&v.velocityEnabled());text(r,"Message","Supports {magnitude}. Preview: "+VectorsText.format(v.velocityTemplate(),12.5),v.velocityTemplate(),n->draft.vectors("velocityTemplate",n),v.enabled()&&v.velocityEnabled());colorScale(r,"Velocity colors",v.velocityColors(),n->draft.vectors("velocityColors",n));appearance(r,6);}reset(r);}

    private void hud(LinearLayout r){title(r,"HUD Studio","Select an element, preview its appearance, or open the screen layout editor.");card(r,"ELEMENTS");tabs(r,HUD);var s=draft.hud.get(hudElement=tab);card(r,"PREVIEW");r.addChild(new HudSampleWidget(contentW,64,draft,hudElement));action(r,"Edit position & size",()->minecraft.gui.setScreen(new HudPlacementScreen(this,draft,hudElement)));card(r,"STYLE");if(hudElement==0){slider(r,"Opacity",null,s.opacity()*100,5,100,1,v->hudChange(s.edit(s.x(),s.y(),s.scale(),s.color(),s.secondaryColor(),s.combinedColor(),s.width(),s.thickness(),v/100)),true);}if(hudElement==1)colorScale(r,"Fall colors",draft.damage.fallColors(),v->draft.damage("fallColors",v));else if(hudElement==2)colorScale(r,"Hit colors",draft.damage.hitColors(),v->draft.damage("hitColors",v));else color(r,"Primary color",s.color(),c->hudChange(s.edit(s.x(),s.y(),s.scale(),c,s.secondaryColor(),s.combinedColor(),s.width(),s.thickness(),s.opacity())));reset(r);}

    private void tracker(LinearLayout r){var t=draft.tracker;title(r,"Player Tracker","Show locator-bar players around the crosshair without sending any client requests.");card(r,"APPEARANCE");slider(r,"Radius","Distance from the crosshair in GUI pixels.",t.radius(),16,160,1,v->draft.tracker("radius",(int)v),t.enabled());slider(r,"Transparency","Opacity of heads, markers, and vertical arrows.",t.opacity()*100,5,100,1,v->draft.tracker("opacity",v/100),t.enabled());slider(r,"Icon size","Player head or color-marker size.",t.iconSize(),6,24,1,v->draft.tracker("iconSize",(int)v),t.enabled());slider(r,"Maximum players","0 shows every available player.",t.maxVisiblePlayers(),0,100,1,v->draft.tracker("maxVisiblePlayers",(int)v),t.enabled());choice(r,"Markers",t.displayMode().label(),()->draft.tracker("displayMode",t.displayMode().next()),t.enabled());card(r,"DISTANCE");slider(r,"Distance scaling","How strongly distant markers shrink.",t.distanceScalingStrength()*100,0,100,1,v->draft.tracker("distanceScalingStrength",v/100),t.enabled());toggle(r,"Show distance","Show the client-visible range beside each marker.",t.showDistance(),v->draft.tracker("showDistance",v),t.enabled());toggle(r,"Hide distant players","Fade and hide players beyond a chosen range.",t.hideDistantPlayers(),v->draft.tracker("hideDistantPlayers",v),t.enabled());slider(r,"Start hiding at","Distance in blocks where fading begins.",t.hideStartDistance(),50,10000,10,v->draft.tracker("hideStartDistance",v),t.enabled()&&t.hideDistantPlayers());card(r,"VISIBILITY");toggle(r,"Only when List Players held","Uses the key currently bound to List Players.",t.onlyWhenPlayerListHeld(),v->draft.tracker("onlyWhenPlayerListHeld",v),t.enabled());toggle(r,"Hide locator bar","Hide the vanilla locator bar whenever this module is enabled.",t.hideLocatorBar(),v->draft.tracker("hideLocatorBar",v),t.enabled());reset(r);}

    private void title(LinearLayout r,String name,String info){r.addChild(new StringWidget(Component.literal(name),font));note(r,info);}private void card(LinearLayout r,String name){r.addChild(new StringWidget(Component.literal(name).withColor(0xff62d8ff),font));}
    private void note(LinearLayout r,String value){r.addChild(new StringWidget(Component.literal(value).withColor(0xffaab6c2),font));}
    private void row(LinearLayout r,String label,String desc,AbstractWidget control,boolean active){var line=LinearLayout.horizontal().spacing(6);var text=LinearLayout.vertical().spacing(1);text.addChild(new StringWidget(Math.max(80,contentW-control.getWidth()-12),10,Component.literal(label).withColor(active?0xffffffff:0xff6f7780),font));if(desc!=null)text.addChild(new StringWidget(Math.max(80,contentW-control.getWidth()-12),10,Component.literal(desc).withColor(active?0xff9ba8b5:0xff59616a),font));control.active=active;line.addChild(text);line.addChild(control);r.addChild(line);}
    private Button button(String text,int width,Button.OnPress press){return Button.builder(Component.literal(text),press).bounds(0,0,width,20).build();}
    private void toggle(LinearLayout r,String label,String desc,boolean value,Consumer<Boolean> set,boolean active){row(r,label,desc,button(value?"On":"Off",58,b->{set.accept(!value);rebuildWidgets();}),active);}
    private void choice(LinearLayout r,String label,String value,Runnable next,boolean active){row(r,label,null,button(value,112,b->{next.run();rebuildWidgets();}),active);}
    private void slider(LinearLayout r,String label,String desc,double value,double min,double max,double step,DoubleConsumer set,boolean active){var s=SettingsControls.slider("",value,min,max,step,132,v->{set.accept(v);if(apply!=null){apply.active=draft.validation().isEmpty();}});row(r,label,desc,s,active);}
    private void text(LinearLayout r,String label,String desc,String value,Consumer<String> set,boolean active){var box=new EditBox(font,0,0,150,20,Component.literal(label));box.setMaxLength(160);box.setValue(value);box.setResponder(v->{set.accept(v);if(apply!=null)apply.active=draft.validation().isEmpty();});row(r,label,desc,box,active);}
    private void template(LinearLayout r,String label,String value,boolean hit){text(r,label,(hit?"Supports {damage} and {blocks}.":"Supports {blocks}.")+" Preview: "+DamageText.format(value,12.5,18),value,v->draft.damage(hit?"hitTemplate":"fallTemplate",v),true);}
    private void color(LinearLayout r,String label,int value,IntConsumer set){var edit=Button.builder(Component.literal("■ Edit").withColor(value),b->minecraft.gui.setScreen(new ColorPickerScreen(this,value,c->{set.accept(c);rebuildWidgets();}))).bounds(0,0,68,20).build();row(r,label,String.format("#%06X",value),edit,true);}
    private void colorScale(LinearLayout r,String label,ColorScale scale,Consumer<ColorScale> set){boolean gearDomain="Hit colors".equals(label)&&draft.damage.useEnemyGear();ColorScale effective=gearDomain?scale.withDomain(0,20):scale;int sample=effective.mode()==ColorMode.FLAT?effective.flatColor():effective.color((effective.minimum()+effective.maximum())/2);String mode=scale.mode()==ColorMode.FLAT?"Flat":"Gradient";var edit=Button.builder(Component.literal("■ "+mode).withColor(sample),b->minecraft.gui.setScreen(new ColorScaleEditorScreen(this,label,scale,gearDomain,v->{set.accept(v);rebuildWidgets();}))).bounds(0,0,92,20).build();row(r,label,mode+(gearDomain?" color rule · 0–20 while using gear":" color rule"),edit,true);}
    private void itemList(LinearLayout r,String label,java.util.List<SurvivalItemRule> items,java.util.List<SurvivalItemRule> defaults,String field){var controls=LinearLayout.horizontal().spacing(4);controls.addChild(new RotatingItemPreview(items));controls.addChild(button("Edit "+items.size(),70,b->minecraft.gui.setScreen(new SurvivalItemEditor(this,label,items,defaults,v->{draft.survival(field,v);rebuildWidgets();}))));var line=LinearLayout.horizontal().spacing(6);line.addChild(new StringWidget(Math.max(80,contentW-118),20,Component.literal(label),font));line.addChild(controls);r.addChild(line);}
    private void tabs(LinearLayout r,String... names){var line=LinearLayout.horizontal().spacing(3);int w=Math.max(44,Math.min(110,(contentW-(names.length-1)*3)/names.length));for(int i=0;i<names.length;i++){int n=i;var b=button((tab==i?"• ":"")+names[i],w,x->{tab=n;rebuildWidgets();});b.active=tab!=i;line.addChild(b);}r.addChild(line);}
    private void appearance(LinearLayout r,int element){card(r,"APPEARANCE");row(r,HUD[element],"Placement and styling in HUD Studio.",button("Open",60,b->{page=8;tab=element;rebuildWidgets();}),true);}
    private void advanced(LinearLayout r,Runnable contents){int key=page*4+Math.min(tab,3);r.addChild(button((expanded[key]?"▾ ":"▸ ")+"Advanced",110,b->{expanded[key]=!expanded[key];rebuildWidgets();}));if(expanded[key])contents.run();}
    private void action(LinearLayout r,String label,Runnable action){r.addChild(button(label,Math.min(190,contentW),b->action.run()));}
    private void reset(LinearLayout r){action(r,"Reset this section",()->confirm("Reset "+PAGES[page]+"?",()->{draft.reset(page);rebuildWidgets();}));}
    private void confirm(String title,Runnable yes){minecraft.gui.setScreen(new SettingsConfirmScreen(this,title,"This changes only the current draft.",yes,()->minecraft.gui.setScreen(this)));}
    private void hudChange(HudStyle style){draft.hud=draft.hud.with(hudElement,style);}
    private void hudCopyPitch(){var s=draft.hud.pitch();draft.hud=draft.hud.with(0,s.edit(s.x(),s.y(),s.scale(),s.color(),s.secondaryColor(),s.combinedColor(),draft.pitch.width(),draft.pitch.thickness(),s.opacity()));}
    private void apply(){try{draft.apply();minecraft.gui.setScreen(parent);}catch(IOException e){error=e.getMessage();rebuildWidgets();}}
    private void closeRequested(){if(!draft.dirty())minecraft.gui.setScreen(parent);else minecraft.gui.setScreen(new SettingsConfirmScreen(this,"Unsaved changes","Apply changes before closing?",this::apply,()->minecraft.gui.setScreen(parent)));}public void onClose(){closeRequested();}
    public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float dt){g.fill(0,0,width,height,0xff0e141b);g.fill(0,0,sidebar,height,0xff171f29);g.fill(sidebar,0,sidebar+1,height,0xff334353);g.fill(sidebar,0,width,35,0xff131b24);super.extractRenderState(g,mx,my,dt);g.text(font,"MACE PVP",13,14,0xff62d8ff);g.text(font,PAGES[page],contentX,14,0xffffffff);String s=!draft.validation().isEmpty()?draft.validation():error;if(!s.isEmpty())g.text(font,s,contentX,height-40,0xffff7777);else if(draft.dirty())g.text(font,"Unapplied changes",contentX,height-40,0xffffc766);}
}
