package dev.macepvpmod;

import java.io.IOException;
import java.util.function.*;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.layouts.LinearLayout;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.input.MouseButtonEvent;
import net.minecraft.network.chat.Component;

/** Complete settings workspace; module pages edit one shared draft directly. */
public final class SettingsScreen extends Screen {
    private static final String[] PAGES={"Overview","Pitch Bar","Damage","Attribute Swaps","Survival","Reach Outlines","HUD Studio"};
    private static final String[] HUD={"Pitch bar","Fall distance","Hit damage","Retotem","Healing","Attribute swap"};
    private final Screen parent;private final SettingsSession draft;private final boolean[] expanded=new boolean[28];private int page,tab,hudElement,sidebar,contentX,contentW;private String error="";private Button apply;private HudRenderer.Bounds previewBounds;private boolean dragging;
    public SettingsScreen(Screen parent){super(Component.translatable("macepvpmod.settings.title"));this.parent=parent;draft=new SettingsSession();}

    protected void init(){sidebar=Math.min(168,Math.max(118,width/3));contentX=sidebar+14;contentW=Math.max(170,width-contentX-14);buildSidebar();var rows=LinearLayout.vertical().spacing(6);
        switch(page){case 0->overview(rows);case 1->pitch(rows);case 2->damage(rows);case 3->swaps(rows);case 4->survival(rows);case 5->reach(rows);case 6->hud(rows);}
        var scroll=new ScrollableLayout(minecraft,rows,Math.max(42,height-94));scroll.setMinWidth(contentW);scroll.arrangeElements();scroll.setX(contentX);scroll.setY(44);scroll.visitWidgets(this::addRenderableWidget);
        int w=84,x=width-14;apply=addRenderableWidget(Button.builder(Component.translatable("macepvpmod.settings.apply"),b->apply()).bounds(x-w*2-6,height-27,w,20).build());apply.active=draft.dirty()&&draft.validation().isEmpty();addRenderableWidget(Button.builder(Component.translatable("macepvpmod.settings.cancel"),b->closeRequested()).bounds(x-w,height-27,w,20).build());}

    private void buildSidebar(){int y=40;for(int i=0;i<PAGES.length;i++){int n=i;int toggle=i>0&&i<6?38:0;addRenderableWidget(Button.builder(Component.literal((page==i?"› ":"")+PAGES[i]),b->{page=n;tab=0;rebuildWidgets();}).bounds(8,y,sidebar-20-toggle,22).build());if(toggle>0)addRenderableWidget(Button.builder(Component.literal(draft.enabled(i)?"✓":"—"),b->{draft.toggle(n);rebuildWidgets();}).bounds(sidebar-48,y,36,22).build());y+=26;}}
    private void overview(LinearLayout r){title(r,"Settings overview","Choose a module on the left. Every edit remains a draft until Apply.");card(r,"MODULE STATUS");for(int i=1;i<6;i++){int n=i;row(r,PAGES[i],draft.enabled(i)?"Enabled":"Disabled",button(draft.enabled(i)?"On":"Off",54,b->{draft.toggle(n);rebuildWidgets();}),true);}card(r,"WORKSPACE");note(r,"Complex color, sound, playlist, and item editors return their result to this same draft.");action(r,"Reset everything",()->confirm("Reset all settings?",()->{draft.resetAll();rebuildWidgets();}));}

    private void pitch(LinearLayout r){title(r,"Elytra Pitch Bar","Keep the common flight guide controls visible; technical tuning is grouped below.");card(r,"GENERAL");toggle(r,"Enabled","Show the pitch guide while gliding.",draft.pitch.enabled(),v->draft.pitch("enabled",v),true);toggle(r,"Third-person view","Also show the guide outside first person.",draft.pitch.thirdPerson(),v->draft.pitch("thirdPerson",v),draft.pitch.enabled());card(r,"FLIGHT GUIDE");slider(r,"Target pitch","The approach angle the center line represents.",draft.pitch.targetPitch(),-90,90,.5,v->draft.pitch("targetPitch",v),draft.pitch.enabled());slider(r,"Response","Pixels moved for each degree away from target.",draft.pitch.sensitivity(),.1,10,.1,v->draft.pitch("sensitivity",v),draft.pitch.enabled());slider(r,"Maximum travel","Limits vertical movement on screen.",draft.pitch.maxDisplacement(),0,200,1,v->draft.pitch("maxDisplacement",(int)v),draft.pitch.enabled());advanced(r,()->{slider(r,"Bar width","Exact width is normally edited in HUD Studio.",draft.pitch.width(),10,400,1,v->{draft.pitch("width",(int)v);hudCopyPitch();},true);slider(r,"Thickness","Bar thickness in GUI pixels.",draft.pitch.thickness(),1,8,1,v->{draft.pitch("thickness",(int)v);hudCopyPitch();},true);});appearance(r,0);reset(r);}

    private void damage(LinearLayout r){title(r,"Damage Counter","Fall, hit, and weapon behavior are separated into focused tabs.");tabs(r,"Fall Distance","Hit Damage","Weapons","Appearance");var d=draft.damage;
        if(tab==0){card(r,"FALL DISTANCE");toggle(r,"Show fall distance","Display damage-relevant fall distance.",d.fallEnabled(),v->draft.damage("fallEnabled",v),d.enabled());slider(r,"Visibility threshold","Show only above this many blocks.",d.fallThreshold(),0,20,.1,v->draft.damage("fallThreshold",v),d.enabled()&&d.fallEnabled());template(r,"Fall message",d.fallTemplate(),false);appearance(r,1);}
        if(tab==1){card(r,"HIT DAMAGE");toggle(r,"Show hit damage","Display confirmed outgoing damage.",d.hitEnabled(),v->draft.damage("hitEnabled",v),d.enabled());slider(r,"Display duration","How long the result remains visible.",d.hitSeconds(),1,10,1,v->draft.damage("hitSeconds",(int)v),d.enabled()&&d.hitEnabled());choice(r,"Damage source",d.calculatedDamage()?"Calculated":"Reported",()->draft.damage("calculatedDamage",!d.calculatedDamage()),d.enabled()&&d.hitEnabled());toggle(r,"Use enemy gear","Estimate visible armor and enchantments; temporarily uses a 0–20 color scale.",d.useEnemyGear(),v->draft.damage("useEnemyGear",v),d.enabled()&&d.hitEnabled()&&d.calculatedDamage());toggle(r,"Bold critical hits","Emphasize confirmed vanilla critical hits.",d.boldCriticalDamage(),v->draft.damage("boldCriticalDamage",v),d.enabled()&&d.hitEnabled());template(r,"Hit message",d.hitTemplate(),true);appearance(r,2);}
        if(tab==2){card(r,"WEAPON FILTER");toggle(r,"Mace","Track mace attacks.",d.maceEnabled(),v->draft.damage("maceEnabled",v),d.enabled()&&d.hitEnabled());toggle(r,"Spear","Track spear jabs and charges.",d.spearEnabled(),v->draft.damage("spearEnabled",v),d.enabled()&&d.hitEnabled());toggle(r,"Sword and axe","Track conventional melee weapons.",d.swordAxeEnabled(),v->draft.damage("swordAxeEnabled",v),d.enabled()&&d.hitEnabled());}
        if(tab==3){card(r,"HUD STUDIO");note(r,"Fall and Hit placement, scale, and color gradients are configured with their HUD elements.");appearance(r,1);appearance(r,2);}reset(r);}

    private void swaps(LinearLayout r){title(r,"Attribute Swaps","Feedback and detection rules are intentionally separate.");card(r,"FEEDBACK");toggle(r,"HUD notification","Show a short overlay message.",draft.swap.visualEnabled(),v->draft.swap("visualEnabled",v),draft.swap.enabled());toggle(r,"Sound","Play feedback when a swap is detected.",draft.swap.soundEnabled(),v->draft.swap("soundEnabled",v),draft.swap.enabled());text(r,"Sound ID","Registered Minecraft sound identifier.",draft.swap.soundId(),v->draft.swap("soundId",v),draft.swap.enabled()&&draft.swap.soundEnabled());action(r,"Test sound",()->AttributeSwaps.playSound(draft.swap.soundId()));card(r,"DETECTION");toggle(r,"Weapons only","Ignore swaps to items without weapon attributes.",draft.swap.weaponOnly(),v->draft.swap("weaponOnly",v),draft.swap.enabled());toggle(r,"Successful hits only","Require combat confirmation before detecting the swap.",draft.swap.successfulHitOnly(),v->draft.swap("successfulHitOnly",v),draft.swap.enabled());appearance(r,5);reset(r);}

    private void survival(LinearLayout r){title(r,"Survival Instincts","Warnings, item rules, and audio are separated into focused tabs.");tabs(r,"Totem","Health & Hunger","Audio");var s=draft.survival;
        if(tab==0){card(r,"TOTEM WARNING");toggle(r,"Retotem warning","Warn when a carried totem can fill an empty offhand.",s.retotemEnabled(),v->draft.survival("retotemEnabled",v),s.enabled());text(r,"Message","Text displayed by the warning.",s.retotemText(),v->draft.survival("retotemText",v),s.enabled()&&s.retotemEnabled());appearance(r,3);}
        if(tab==1){card(r,"TRIGGERS");toggle(r,"Health and hunger warnings","Enable actionable survival alerts.",s.healingEnabled(),v->draft.survival("healingEnabled",v),s.enabled());slider(r,"Low health","Trigger below this percentage.",s.healthPercent(),0,100,1,v->draft.survival("healthPercent",v),s.enabled()&&s.healingEnabled());slider(r,"Low saturation","Trigger below this saturation value.",s.saturationThreshold(),0,20,.5,v->draft.survival("saturationThreshold",v),s.enabled()&&s.healingEnabled());card(r,"MESSAGES");text(r,"Low health",null,s.healthText(),v->draft.survival("healthText",v),true);text(r,"Low saturation",null,s.saturationText(),v->draft.survival("saturationText",v),true);text(r,"Combined",null,s.combinedText(),v->draft.survival("combinedText",v),true);card(r,"ACTIONABLE ITEMS");itemList(r,"Healing items",s.healingItems(),SurvivalItemRule.healingDefaults(),"healingItems");itemList(r,"Saturation items",s.saturationItems(),SurvivalItemRule.saturationDefaults(),"saturationItems");appearance(r,4);}
        if(tab==2){card(r,"PLAYLIST");row(r,"Warning sounds","One entry plays on each warning beat.",button("Edit "+s.sounds().size(),72,b->minecraft.gui.setScreen(new SoundPlaylistScreen(this,s.sounds(),v->{draft.survival("sounds",v);rebuildWidgets();}))),true);advanced(r,()->{slider(r,"Threshold interval","Seconds between notes at the warning threshold.",s.audioStartInterval(),.05,3,.05,v->draft.survival("audioStartInterval",v),true);slider(r,"Critical interval","Seconds between notes near zero health.",s.audioEndInterval(),.05,3,.05,v->draft.survival("audioEndInterval",v),true);});}reset(r);}

    private void reach(LinearLayout r){title(r,"Reach Outlines","Detection and rendering have separate visual hierarchy.");card(r,"DETECTION");toggle(r,"Top faces only","Ignore side and bottom faces.",draft.reach.topFacesOnly(),v->draft.reach("topFacesOnly",v),draft.reach.enabled());choice(r,"Hard-to-reach faces",draft.reach.hardToReachMode().label(),()->draft.reach("hardToReachMode",draft.reach.hardToReachMode().next()),draft.reach.enabled());slider(r,"Minimum reachable area","Required reachable fraction of a face.",draft.reach.minimumReachableArea()*100,1,100,1,v->draft.reach("minimumReachableArea",v/100),draft.reach.enabled());card(r,"RENDERING");slider(r,"Intensity","Outline opacity.",draft.reach.intensity()*100,2,100,1,v->draft.reach("intensity",v/100),draft.reach.enabled());slider(r,"Thickness","Outline width in pixels.",draft.reach.thickness(),1,ReachOutlineConfig.MAX_THICKNESS,1,v->draft.reach("thickness",(int)v),draft.reach.enabled());color(r,"Outline color",draft.reach.color(),c->draft.reach("color",c));reset(r);}

    private void hud(LinearLayout r){title(r,"HUD Studio","Select an element, tune it here, and use the live samples behind the panel.");card(r,"ELEMENTS");tabs(r,HUD);var s=draft.hud.get(hudElement=tab);card(r,"POSITION & SIZE");slider(r,"Horizontal offset","Fine positioning from its anchor.",s.x(),-400,400,1,v->hudChange(s.edit(v,s.y(),s.scale(),s.color(),s.secondaryColor(),s.combinedColor(),s.width(),s.thickness(),s.opacity())),true);slider(r,"Vertical offset","Fine positioning from its anchor.",s.y(),-400,400,1,v->hudChange(s.edit(s.x(),v,s.scale(),s.color(),s.secondaryColor(),s.combinedColor(),s.width(),s.thickness(),s.opacity())),true);slider(r,hudElement==0?"Width":"Scale",null,hudElement==0?s.width():s.scale(),hudElement==0?10:.5,hudElement==0?400:4,hudElement==0?1:.05,v->hudChange(s.edit(s.x(),s.y(),hudElement==0?s.scale():v,s.color(),s.secondaryColor(),s.combinedColor(),hudElement==0?(int)v:s.width(),s.thickness(),s.opacity())),true);if(hudElement==0){slider(r,"Thickness",null,s.thickness(),1,8,1,v->hudChange(s.edit(s.x(),s.y(),s.scale(),s.color(),s.secondaryColor(),s.combinedColor(),s.width(),(int)v,s.opacity())),true);slider(r,"Opacity",null,s.opacity()*100,5,100,1,v->hudChange(s.edit(s.x(),s.y(),s.scale(),s.color(),s.secondaryColor(),s.combinedColor(),s.width(),s.thickness(),v/100)),true);}card(r,"COLOR");if(hudElement==1)colorScale(r,"Fall colors",draft.damage.fallColors(),v->draft.damage("fallColors",v));else if(hudElement==2)colorScale(r,"Hit colors",draft.damage.hitColors(),v->draft.damage("hitColors",v));else color(r,"Primary color",s.color(),c->hudChange(s.edit(s.x(),s.y(),s.scale(),c,s.secondaryColor(),s.combinedColor(),s.width(),s.thickness(),s.opacity())));reset(r);}

    private void title(LinearLayout r,String name,String info){r.addChild(new StringWidget(Component.literal(name),font));note(r,info);}private void card(LinearLayout r,String name){r.addChild(new StringWidget(Component.literal(name).withColor(0xff62d8ff),font));}
    private void note(LinearLayout r,String value){r.addChild(new StringWidget(Component.literal(value).withColor(0xffaab6c2),font));}
    private void row(LinearLayout r,String label,String desc,AbstractWidget control,boolean active){var line=LinearLayout.horizontal().spacing(6);var text=LinearLayout.vertical().spacing(1);text.addChild(new StringWidget(Math.max(80,contentW-control.getWidth()-12),10,Component.literal(label).withColor(active?0xffffffff:0xff6f7780),font));if(desc!=null)text.addChild(new StringWidget(Math.max(80,contentW-control.getWidth()-12),10,Component.literal(desc).withColor(active?0xff9ba8b5:0xff59616a),font));control.active=active;line.addChild(text);line.addChild(control);r.addChild(line);}
    private Button button(String text,int width,Button.OnPress press){return Button.builder(Component.literal(text),press).bounds(0,0,width,20).build();}
    private void toggle(LinearLayout r,String label,String desc,boolean value,Consumer<Boolean> set,boolean active){row(r,label,desc,button(value?"On":"Off",58,b->{set.accept(!value);rebuildWidgets();}),active);}
    private void choice(LinearLayout r,String label,String value,Runnable next,boolean active){row(r,label,null,button(value,112,b->{next.run();rebuildWidgets();}),active);}
    private void slider(LinearLayout r,String label,String desc,double value,double min,double max,double step,DoubleConsumer set,boolean active){var s=SettingsControls.slider("",value,min,max,step,132,v->{set.accept(v);if(apply!=null){apply.active=draft.validation().isEmpty();}});row(r,label,desc,s,active);}
    private void text(LinearLayout r,String label,String desc,String value,Consumer<String> set,boolean active){var box=new EditBox(font,0,0,150,20,Component.literal(label));box.setMaxLength(160);box.setValue(value);box.setResponder(v->{set.accept(v);if(apply!=null)apply.active=draft.validation().isEmpty();});row(r,label,desc,box,active);}
    private void template(LinearLayout r,String label,String value,boolean hit){text(r,label,(hit?"Supports {damage} and {blocks}.":"Supports {blocks}.")+" Preview: "+DamageText.format(value,12.5,18),value,v->draft.damage(hit?"hitTemplate":"fallTemplate",v),true);}
    private void color(LinearLayout r,String label,int value,IntConsumer set){var edit=Button.builder(Component.literal("■ Edit").withColor(value),b->minecraft.gui.setScreen(new ColorPickerScreen(this,value,c->{set.accept(c);rebuildWidgets();}))).bounds(0,0,68,20).build();row(r,label,String.format("#%06X",value),edit,true);}
    private void colorScale(LinearLayout r,String label,ColorScale scale,Consumer<ColorScale> set){boolean gearDomain="Hit colors".equals(label)&&draft.damage.useEnemyGear();ColorScale effective=gearDomain?scale.withDomain(0,20):scale;int sample=effective.mode()==ColorMode.FLAT?effective.flatColor():effective.color((effective.minimum()+effective.maximum())/2);String mode=scale.mode()==ColorMode.FLAT?"Flat":"Gradient";var edit=Button.builder(Component.literal("■ "+mode).withColor(sample),b->minecraft.gui.setScreen(new ColorScaleEditorScreen(this,label,scale,gearDomain,v->{set.accept(v);rebuildWidgets();}))).bounds(0,0,92,20).build();row(r,label,mode+(gearDomain?" color rule · 0–20 while using gear":" color rule"),edit,true);}
    private void itemList(LinearLayout r,String label,java.util.List<SurvivalItemRule> items,java.util.List<SurvivalItemRule> defaults,String field){var controls=LinearLayout.horizontal().spacing(4);controls.addChild(new RotatingItemPreview(items));controls.addChild(button("Edit "+items.size(),70,b->minecraft.gui.setScreen(new SurvivalItemEditor(this,label,items,defaults,v->{draft.survival(field,v);rebuildWidgets();}))));var line=LinearLayout.horizontal().spacing(6);line.addChild(new StringWidget(Math.max(80,contentW-118),20,Component.literal(label),font));line.addChild(controls);r.addChild(line);}
    private void tabs(LinearLayout r,String... names){var line=LinearLayout.horizontal().spacing(3);int w=Math.max(44,Math.min(110,(contentW-(names.length-1)*3)/names.length));for(int i=0;i<names.length;i++){int n=i;var b=button((tab==i?"• ":"")+names[i],w,x->{tab=n;rebuildWidgets();});b.active=tab!=i;line.addChild(b);}r.addChild(line);}
    private void appearance(LinearLayout r,int element){card(r,"APPEARANCE");row(r,HUD[element],"Placement and styling in HUD Studio.",button("Open",60,b->{page=6;tab=element;rebuildWidgets();}),true);}
    private void advanced(LinearLayout r,Runnable contents){int key=page*4+Math.min(tab,3);r.addChild(button((expanded[key]?"▾ ":"▸ ")+"Advanced",110,b->{expanded[key]=!expanded[key];rebuildWidgets();}));if(expanded[key])contents.run();}
    private void action(LinearLayout r,String label,Runnable action){r.addChild(button(label,Math.min(190,contentW),b->action.run()));}
    private void reset(LinearLayout r){action(r,"Reset this section",()->confirm("Reset "+PAGES[page]+"?",()->{draft.reset(page);rebuildWidgets();}));}
    private void confirm(String title,Runnable yes){minecraft.gui.setScreen(new SettingsConfirmScreen(this,title,"This changes only the current draft.",yes,()->minecraft.gui.setScreen(this)));}
    private void hudChange(HudStyle style){draft.hud=draft.hud.with(hudElement,style);}
    private void hudCopyPitch(){var s=draft.hud.pitch();draft.hud=draft.hud.with(0,s.edit(s.x(),s.y(),s.scale(),s.color(),s.secondaryColor(),s.combinedColor(),draft.pitch.width(),draft.pitch.thickness(),s.opacity()));}
    private void renderHudPreview(GuiGraphicsExtractor g){var s=draft.hud.get(hudElement);previewBounds=switch(hudElement){case 0->HudRenderer.pitch(g,s,draft.pitch,draft.pitch.targetPitch());case 1->HudRenderer.textColor(g,DamageText.format(draft.damage.fallTemplate(),12.5,18),s,draft.damage.fallColors().color(12.5));case 2->HudRenderer.textColor(g,DamageText.format(draft.damage.hitTemplate(),12.5,18),s,draft.damage.effectiveHitColors().color(18));case 3->HudRenderer.text(g,draft.survival.retotemText(),s,0);case 4->HudRenderer.text(g,draft.survival.healthText(),s,1);default->HudRenderer.text(g,AttributeSwaps.HUD_TEXT,s,0);};if(previewBounds!=null){int x=(int)previewBounds.x()-2,y=(int)previewBounds.y()-2,r=(int)(previewBounds.x()+previewBounds.width())+2,b=(int)(previewBounds.y()+previewBounds.height())+2;g.fill(x,y,r,y+1,0xff62d8ff);g.fill(x,b,r,b+1,0xff62d8ff);g.fill(x,y,x+1,b,0xff62d8ff);g.fill(r,y,r+1,b,0xff62d8ff);}}
    public boolean mouseClicked(MouseButtonEvent e,boolean twice){if(super.mouseClicked(e,twice))return true;if(page==6&&e.button()==0&&previewBounds!=null&&previewBounds.contains(e.x(),e.y())){dragging=true;setFocused(null);return true;}return false;}
    public boolean mouseDragged(MouseButtonEvent e,double dx,double dy){if(dragging){var s=draft.hud.get(hudElement);hudChange(s.edit(s.x()+dx,s.y()+dy,s.scale(),s.color(),s.secondaryColor(),s.combinedColor(),s.width(),s.thickness(),s.opacity()));return true;}return super.mouseDragged(e,dx,dy);}
    public boolean mouseReleased(MouseButtonEvent e){dragging=false;return super.mouseReleased(e);}
    private void apply(){try{draft.apply();minecraft.gui.setScreen(parent);}catch(IOException e){error=e.getMessage();rebuildWidgets();}}
    private void closeRequested(){if(!draft.dirty())minecraft.gui.setScreen(parent);else minecraft.gui.setScreen(new SettingsConfirmScreen(this,"Unsaved changes","Apply changes before closing?",this::apply,()->minecraft.gui.setScreen(parent)));}public void onClose(){closeRequested();}
    public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float dt){g.fill(0,0,width,height,0xff0e141b);if(page==6)renderHudPreview(g);g.fill(0,0,sidebar,height,0xff171f29);g.fill(sidebar,0,sidebar+1,height,0xff334353);g.fill(sidebar,0,width,35,0xff131b24);super.extractRenderState(g,mx,my,dt);g.text(font,"MACE PVP",13,14,0xff62d8ff);g.text(font,PAGES[page],contentX,14,0xffffffff);String s=!draft.validation().isEmpty()?draft.validation():error;if(!s.isEmpty())g.text(font,s,contentX,height-40,0xffff7777);else if(draft.dirty())g.text(font,"Unapplied changes",contentX,height-40,0xffffc766);}
}
